### ISSUE TITLE
Slow response times and EIPFS CIDS no longer available

### ISSUE THREAD

**Issue by TorfinnOlsen** [ipni/storetheindex#1310] opened 2023-02-22 17:14 UTC
Alan Shaw posted a not in the #IPNI slack that he's seeing very slow response times for the same endpoint but different CIDs.

Sample CID: bafybeidf7igbd7pu46s6obhzvzpmjsoogn2gaqxgeuh2wlxbmrosvndcv4

I duplicated the issue on my machine and timeouts don't seem to be triggering.

https://cid.contact/cid/bafybeidf7igbd7pu46s6obhzvzpmjsoogn2gaqxgeuh2wlxbmrosvndcv4

Timing appears to coincide with caskaDHT rollout:

![image](https://user-images.githubusercontent.com/117677176/220704666-27e7619c-b3de-42c7-ae52-41bdd48a59f7.png)

**Comment by masih** [comment] 2023-02-22 20:20
The cause of this was two of the heavy weight clients getting assigned to the same node. Assignment currently happens at random. To fix the issue the node is now moved to cpu optimised instance types and the publishers are in the process of reassignment to avoid hotspots. 

As far as client impact, service is now restored.

**Comment by masih** [comment] 2023-02-22 20:48
Re assignment is now complete. closing. Please feel free to reopen if there is anything that I might have missed.

**Closed by masih** 2023-02-22 20:48 UTC
