### ISSUE TITLE
Gap in ingesting long chains

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#765] opened 2022-09-07 09:06 UTC
When download of long chains is interrupted, on resumption and completion of download it seems the indexer node only processes a fraction of unprocessed ads. This is observed on nodes dedicated to ingesting nft.storage.

Potentially related: https://github.com/filecoin-project/go-legs/pull/153

* Write tests to reproduce this, starting from HTTP publisher.
* Check logs from `oden` and `Vega` for clues.

**Comment by gammazero** [comment] 2022-09-22 16:36
Before sync is interrupted:
```
{"level":"info","ts":"2022-09-18T22:15:41.639Z","logger":"indexer/ingest","caller":"ingest/ingest.go:948","msg":"Processing advertisement","adCid":"baguqeerartfbylj56uph5433dlf5wqncy2ulkvv3piuk7le2f5r43cqnktzq","publisher":"QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC","progress":"4399013 of 5338000"}
```

After resuming sync:
```
{"level":"info","ts":"2022-09-18T22:15:52.417Z","logger":"indexer/ingest","caller":"ingest/ingest.go:948","msg":"Processing advertisement","adCid":"baguqeera3luh52bw7ml3ysrr7vpissult6x6phocoimy73mdrshhpptan4ma","publisher":"QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC","progress":"1 of 2000"}
```

Note: 2000 is the configured value of `Ingest.SyncSegmentDepthLimit`

**Comment by masih** [comment] 2022-09-22 16:52
Considering the segmented [2K sync returned normally](https://protocollabs.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Benvironment%3D%5C%22prod%5C%22,%20namespace%3D%5C%22storetheindex%5C%22,%20pod_name%3D~%5C%22%28oden%29.%2B%5C%22%7D%20%7C~%20%5C%22Segmented%20sync%20completed%5C%22%5Cn%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221662681966362%22,%22to%22:%221662733628218%22%7D%7D), [looking at the break logic](https://github.com/filecoin-project/go-legs/blob/main/subscriber.go#L1037-L1053) it means one of the following happened:
* There was no call to syncActions or the call explicitly set `nextSyncCid` to `cid.Undef`.
* `nextSyncCid` matched the stop node set in the selector
   * I think because there was _some already processed ad_ the stop node must have been passed into the selector by storetheindex.
* `depthSoFar` i.e. the total traversed depth was larger than or equal to the depth specified in the given selector.

**Comment by masih** [comment] 2022-09-22 17:25
Looking at the [logs](https://protocollabs.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Benvironment%3D%5C%22prod%5C%22,%20namespace%3D%5C%22storetheindex%5C%22,%20pod_name%3D~%5C%22%28oden%29.%2B%5C%22%7D%20%7C~%20%5C%22Segmented%20sync%20completed%5C%22%5Cn%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221662681966362%22,%22to%22:%221662733628218%22%7D%7D) also why there is a `Segmented sync completed` for 5.3M and then ~4m after three is another `Segmented sync completed` for 2K ads for the same provider? 🤔

**Comment by gammazero** [comment] 2022-09-23 14:09
Also note that the ad where the interruption happened does get synced sometime later as part of syncing to a new head:
```
{"level":"info","ts":"2022-09-21T13:38:36.291Z","logger":"indexer/ingest","caller":"ingest/ingest.go:953","msg":"Processing advertisement","adCid":"baguqeerartfbylj56uph5433dlf5wqncy2ulkvv3piuk7le2f5r43cqnktzq","publisher":"QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC","progress":"1 of 1102803"}
```
That ad is successfully ingested.

**Comment by gammazero** [comment] 2022-09-23 14:36
> also why there is a Segmented sync completed for 5.3M and then ~4m after three is another Segmented sync completed for 2K ads for the same provider?

The first one (for 5.4M) was a sync that apparently took a long time, long enough to trigger the auto-sync 2m before the first one finished.  The second sync completion was the auto-sync completing.

**Comment by gammazero** [comment] 2022-10-12 21:23
Cannot reproduce a gap in the chain, or show that any exists on any indexer, so lowering the priority of this issue.

**Comment by gammazero** [comment] 2022-12-06 04:50
Recommend closing this as it appears to be a result of polling and auto-sync happening during a prolonged time of traversing an ad chain tens of thousands of ads long.

**Comment by gammazero** [comment] 2023-01-12 19:59
Closing as per the previous comment.

**Closed by gammazero** 2023-01-12 19:59 UTC
Labels: P3
